site_name: Physics Alumni Scholarship
site_description: An Alumni based scholarship to help needy students
site_url: https://pas-uok.github.io
site_author: Hamza Hanif
site_dir: pas

repo_name: Github
repo_url: https://github.com/pas-uok/pas-uok.github.io
edit_uri: tree/main/site

nav:
  - Introduction: "index.md"
  - About us: "team.md"
  # - Setup: setup.md
  - Recipients:
      - Fall 2021: recipient/fall2021.md
      - Spring 2022: recipient/spring2022.md
      - Fall 2022: recipient/fall2022.md
      - Spring 2023: recipient/spring2023.md
      - Fall 2023: recipient/fall2023.md
      - Spring 2024: recipient/spring2024.md
      - Fall 2024: recipient/fall2024.md


theme:
  name: material
  icon:
    logo: material/atom
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.top
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode




plugins:
  - search
  - markdownextradata
  - autorefs


markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.arithmatex
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: "!!python/name:mermaid2.fence_mermaid"
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: "#"

extra_javascript:
  - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML"

